version: '4.0'
services:
  spring_security:
     image: mysql:8.3.0
     container_name: spring_security_container
     environment:
        MYSQL_DATABASE: SPRINGSECURITY
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: spring_user
        MYSQL_PASSWORD: userpassword
     ports:
        - "3307:3306"
     volumes:
        - ./mysql_data:/var/lib/mysql

volumes:
   mysql_data:
      